{{- $sso := .Values.global.ssoConfig -}}
{{- if and $sso.createSecret (not (empty $sso.providers)) -}}
{{- $secretName := default (printf "%s-sso" (include "inventree.fullname" .)) $sso.providerSecretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "inventree.labels" . | nindent 4 }}
type: Opaque
stringData:
  providers: {{ $sso.providers | toJson | quote }}
{{- end }}
